// <auto-generated />
namespace com.pharmscription.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MAdeSigndateoptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAdeSigndateoptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201604251637458_MAde Signdate optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
